apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  namespace: default # Namespace where the ReplicaSet will be created
  labels:
    app: myapp
    type: front-end
spec:
  template: # This is just the definition of a pod, without apiVersion and kind
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end # The ReplicaSet will match this label, any pods with it will be managed by this ReplicaSet
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3 # Number of pods that should be running at all times
  selector: # This is a label selector to identify the pods managed by this ReplicaSet
    matchLabels:
      type: front-end # This selector matches the label on the pod template above