apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  namespace: default # Namespace where the ReplicationController will be created
  labels:
    app: myapp
    type: front-end
spec:
  template: # This is just the definition of a pod, without apiVersion and kind
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3 # Number of pods that should be running at all times
