apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort # Can also be ClusterIP or LoadBalancer
  ports:
    - port: 80 # This is the port on the service itself
      targetPort: 80 # This is the port on the pod that the service will forward traffic to
      nodePort: 30008 # This is the port on the node that will forward traffic to the service. This is only needed if type is NodePort or LoadBalancer
  selector:
    app: myapp # This selector matches the label on the pod definition
    type: front-end # This selector matches the label on the pod definition