apiVersion: v1
kind: ResourceQuota
metadata:
  name: myapp-quota
  namespace: test # Namespace where the ResourceQuota will be created
spec:
  hard:
    pods: "10" # Total number of pods in the namespace
    requests.cpu: "4" # Total CPU requested by all pods in the namespace
    requests.memory: "4Gi" # Total memory requested by all pods in the namespace, Gi stands for gibibytes and is equivalent to 1024^3 bytes in base 2
    limits.cpu: "10" # Total CPU limit for all pods in the namespace
    limits.memory: "10Gi" # Total memory limit for all pods in the namespace
