apiVersion: v1 # Correct version for a Pod kind
kind: Pod # The kind of resource
metadata:
  name: myapp-pod # Name of the Pod
  namespace: default # Namespace where the Pod will be created
  labels: # This can have ANY key/values, app and type are just examples
    app: myapp # Label for the app name
    type: frontend # Label for the app type
spec:
  containers: # List of containers in the Pod
    - name: myapp-container # Name of the container
      image: myapp-image:latest # Image to use for the container
      env: # Environment variables to set in the container
        - name: ENV_VAR_NAME # Name of the environment variable
          value: ENV_VAR_VALUE # Value of the environment variable

